### ISSUE TITLE
UnsatisfiedDependencyException: Unable to resolve 'username' attribute in Account entity

### ISSUE THREAD

**Issue by hemantgarg1452** [hemantgarg1452/Banking-Application#1]
I am encountering an UnsatisfiedDependencyException while trying to run my Spring Boot application. The error seems to stem from an inability to resolve the username attribute in my Account entity, which is causing issues during bean initialization.

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfig': Unsatisfied dependency expressed through field 'accountService': Error creating bean with name 'accountService': Unsatisfied dependency expressed through field 'accountRepository': Error creating bean with name 'accountRepository' defined in com.example.bankapp.repository.AccountRepository defined in @EnableJpaRepositories declared on BankappApplication: Could not create query for public abstract java.util.Optional com.example.bankapp.repository.AccountRepository.findByUsername(java.lang.String); Reason: Failed to create query for method public abstract java.util.Optional com.example.bankapp.repository.AccountRepository.findByUsername(java.lang.String); Could not resolve attribute 'username' of 'com.example.bankapp.model.Account'
`

`
### Steps to Reproduce
1. Clone the repository.
2. Set up the project as per the instructions.
3. Run the application.

### Current Setup
- **Account Entity**: (Include relevant code)
- **Account Repository**: (Include relevant code)
- **Application Properties**: (Include relevant settings)

### Troubleshooting Steps Taken
- Verified that the `username` field exists in the `Account` entity.
- Checked the database schema to confirm the column exists.
- Cleaned and rebuilt the project.

Any help would be greatly appreciated!
`

**Comment by MohamedAliBouhaouala** [comment]
Please check the following PR: 
https://github.com/hemantgarg1452/Banking-Application/pull/2

**Comment by hemantgarg1452** [comment]
It works.... but when i start application on port 8080... it shows a simple login text instead of login page...
